baseURL: 'https://adrielkuek.github.io/'
locale: en
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
title: 'Adriel Kuek'
theme: "hugo-narrow"

hasCJKLanguage: false
enableEmoji: false

mainSections: ["posts"]

permalinks:
  posts: /posts/:slug/
  pages: /:slug/

pagination:
  pagerSize: 6
  path: "page"

taxonomies:
  author: authors
  tag: tags
  category: categories
  series: series

markup:
  tableOfContents:
    startLevel: 2
    endLevel: 4
    ordered: false
  goldmark:
    renderer:
      unsafe: true
    extensions:
      extras:
        delete:
          enable: true
        insert:
          enable: true
        mark:
          enable: true
        subscript:
          enable: true
        superscript:
          enable: true
      strikethrough: true
  highlight:
    codeFences: true
    guessSyntax: false
    lineNos: false
    lineNumbersInTable: false
    noClasses: false
    style: github
    tabWidth: 2

outputs:
  home: ["HTML", "RSS", "JSON", "WebAppManifest"]

outputFormats:
  WebAppManifest:
    mediaType: "application/manifest+json"
    baseName: "site"
    isPlainText: true

module:
  hugoVersion:
    extended: true
    min: 0.158.0
