# Navigation Links
#   To link a homepage section, use `/#<section-id>` where <section-id> matches the
#   `id:` of a section in `content/_index.md`.

main:
  - name: Bio
    url: /
    weight: 10
  - name: Research
    url: /#research
    weight: 20
  - name: Publications
    url: /#publications
    weight: 30
  - name: Experience
    url: experience/
    weight: 40
